#let conclusions_and_reflections = [
= Conclusions and Reflections

The Shape of Sound resulted in a complete web-based application that demonstrates a visual-first approach to audio synthesis through interactive shape manipulation. The project set out to explore whether a synesthetic interface could make sound design more intuitive without removing creative depth, and the final artefact shows that this approach is both technically viable and creatively meaningful. Through the completed system, users are able to shape sound through visual properties, receive immediate audio feedback, save and export ideas, and engage with synthesis through a workflow that differs from conventional parameter-first software. As a result, the project can be understood both as a working creative tool and as a practice-led investigation into how interaction design can reshape the experience of learning and exploring sound.

The main findings of the project suggest that a visual-first synthesis interface can reduce perceived complexity while still supporting creative exploration. Functional testing showed that the core user-facing features of the application behaved reliably, while user testing indicated that participants generally found the system approachable, useful, and especially effective when key-lock was active. These findings are significant because they support the central premise of the project: that direct visual interaction and immediate audio feedback can make synthesis feel less intimidating without reducing it to a toy-like experience. At the same time, the testing also showed that clarity remains an important issue, particularly in relation to first-use understanding, control-point visibility, and visual feedback around note and key behaviour. This means that the project's concept appears strong, but its long-term success depends on continued refinement of communication and onboarding.

In relation to the project objectives, the outcomes were largely successful. The project did develop a meaningful model for mapping visual properties to audio synthesis behaviour, and this model was implemented in a functioning web application rather than remaining at the level of concept or prototype. The final artefact also provides evidence that the approach can support beginner accessibility, as the user testing results indicate strong scores for approachability, intuitiveness, and melodic support through key lock. The project also demonstrated value for more experienced users, particularly as a sketchpad for rapid sound exploration and idea generation. However, not all objectives were fulfilled equally. While the core synesthetic interaction model, saving, and export were delivered successfully, some aspects of the experience still need refinement, and the sequencer originally considered in earlier planning was not included in the final scope. This means the project met its main objectives strongly in relation to interaction design and usability, while leaving some wider workflow ambitions for future development.

One of the main strengths of the project is the coherence of its central concept. The relationship between visual shape manipulation and audible change remained clear throughout the final design, which helped the application feel like a distinct instrument rather than a collection of disconnected controls. This coherence was strengthened by the immediate audio-visual feedback provided during interaction, as well as by practical features such as key lock, saving, and export, which extended the usefulness of the system beyond a purely conceptual demonstration. Another strength is that the project was able to address both intended audiences at once: beginners were supported through a more approachable and less intimidating interface, while experienced producers could still use the application as a source of rapid experimentation and creative ideation. The final product is therefore strongest where its educational and creative aims overlap, showing that accessibility and expressive potential do not necessarily have to be treated as opposites.

Despite its strengths, the project also has clear limitations. The final application is strongest as an ideation and exploratory sound-design tool rather than as a full replacement for established music production software. This is partly a result of design choice, as the project prioritised intuitive interaction and accessibility over exhaustive synthesis depth, but it also means that some users may find the system narrower than a conventional DAW or dedicated synthesizer. User testing further showed that, although the core concept was well received, first-use clarity still requires improvement, particularly around control-point interaction, keyboard visibility during key-lock use, and the communication of parameter ranges. The evaluation itself is also limited in scale, as the structured user testing involved only five participants, which is enough to identify useful patterns but not enough to support broad generalisation. In addition, the sequencer originally considered in earlier planning was not included in the final scope, meaning that the project currently supports sound creation and idea generation more strongly than wider composition and arrangement workflows. These limitations do not undermine the value of the project, but they do define its current boundaries and show where further development would be most beneficial.

The project also led to substantial learning across both technical and design-focused areas. Existing experience in React-based web development and TypeScript provided a strong foundation for the broader application structure, but much of the project required development beyond familiar full-stack patterns. In particular, the project involved deeper learning in browser-based audio, visual interaction design, audio-visual synchronisation, and the practical challenges of turning a creative prototype into a more complete product. It also strengthened my understanding of how interface design decisions affect not only usability, but also how users interpret and learn complex concepts such as synthesis. Perhaps most importantly, the project reinforced the value of iterative prototyping as a way of generating design knowledge through practice, rather than assuming that interaction decisions can be resolved purely through planning alone.

Future work should focus on refinement and extension rather than replacing the core concept of the project. The most immediate priority is improving first-use clarity through better onboarding, more explicit visual guidance, clearer scale indication on the colour keyboard, and stronger communication of how the main controls affect sound. A larger and more accessibility-aware evaluation would also allow the findings on accessibility, intuitiveness, and creative usefulness to be tested with a broader sample. Beyond refinement, the most obvious functional extension is the sequencer, which was part of earlier planning but not included in the final delivered scope. Adding a sequencer would allow the project to move further from idea generation into composition and arrangement, making it more useful within wider music-production workflows. Other potential developments include richer melodic assistance, more advanced visual feedback, and further exploration of how visual interaction could support understanding of more complex synthesis behaviour. These developments would move the application closer to functioning as a more complete creative environment, whereas the current implementation is strongest as a tool used alongside a DAW rather than as a replacement for one.

Overall, the project demonstrates that visual-first sound design can function as a credible and valuable direction for accessible music technology, while also revealing clear opportunities for future refinement and expansion.

/*
1. opening conclusion paragraph
2. findings and what they mean
3. evaluation against objectives
4. strengths
5. weaknesses/limitations
6. skills/learning
7. future work
8. short closing sentence
*/

/*
Guidance:
- 1000 words
- provide critical reflections on all aspects of project lifecycle
- include conclusions on resulting application and research/findings
- evaluate how effectively your results meet stated objectives
- reflect on strengths and weaknesses of implementation
- discuss acquisition of new knowledge and skills
- consider further work and future recommendations
*/
]
