#let legal_social_sustainability_and_ethical_issues = [
= Legal, Social, Sustainability, and ethical issues

The project raises several legal issues, particularly around data protection and inclusive access. Because the final application includes user accounts, saved ideas, and public sharing by URL, user data must be handled carefully and only to the extent necessary for the functioning of the system. This means personal data should be limited, stored appropriately, and protected against unauthorised access. Inclusive design is also relevant as a legal and practical concern, because a creative tool that claims to reduce barriers to entry should not itself introduce barriers through poor accessibility or unnecessarily complex interaction.

Ethically, the most important issues are connected to user testing and research participation. The project involved collecting feedback from participants in order to evaluate usability and creative usefulness, so consent and voluntary participation were essential. Participants needed to understand the purpose of the testing, what they were being asked to do, and that their involvement was optional. Anonymity was also important in reporting results, particularly in this report itself, where feedback must be discussed without exposing unnecessary personal detail. No sensitive personal data was required for the user testing process, and participants must have the right to withdraw their feedback if they no longer wish to be included. These measures help ensure that the evaluation of the project is ethically proportionate and respectful to those taking part.

The social dimension of the project is closely tied to its central aims. The Shape of Sound was designed to lower barriers to music production, make synthesis less intimidating, and support creative confidence for people who may be discouraged by conventional digital audio workstations. In this sense, the project has a positive social aim: widening access to creative technology by presenting sound design in a more approachable and visually legible form. At the same time, this introduces a responsibility to avoid overclaiming what the application can do. A more accessible interface can support learning and experimentation, but it does not remove the need for musical practice or replace the broader knowledge involved in production. For experienced users, the social value of the tool is in creative exploration and alternative workflows rather than basic accessibility.

The sustainability implications of the project are comparatively limited. As a browser-based application, the system avoids the need for specialised hardware and can be accessed through common devices, which may reduce some barriers associated with software installation or high-end equipment. However, this does not in itself make the project sustainable. The application still depends on web infrastructure, client processing, database hosting, and online services, which all have energy and resource costs.

Security and professional responsibility are also central to the final product. Because the system includes accounts and persistence, authentication and session management must be handled securely. Better Auth, schema validation through Zod, ownership checks on saved ideas, and rate limiting all contribute to reducing obvious risks such as invalid requests, unauthorised modification, or abuse of endpoints. It is also important to represent the implementation honestly. The project makes use of established frameworks, libraries, and documented technical patterns, and these should be acknowledged rather than presented as wholly original inventions. The responsibility of the project is both to protect users and their data through careful engineering, and to describe the technical work accurately and transparently within the dissertation.

/*
Guidance:
- 500 words
- consider legal, ethical, social, professional, sustainability, and security issues associated with your research and the app you are building
*/
]
